{
	"_Type": "Action.Type.CheckRequiredFields",
	"ActionResult": {
		"_Name": "CheckFieldsAddPlayer"
	},
	"OnFailure": "/nba/Actions/FailCheckFieldsAddPlayer.action",
	"OnSuccess": "/nba/Rules/CheckPlayerData.js",
	"RequiredFields": [
		"DPFechaNacimiento",
		"FCApellido",
		"FCDorsal",
		"FCNombre",
		"FCPeso",
		"FCPosicion",
		"LPNacionalidad",
		"FCAltura"
	]
}