{
	"_Type": "Action.Type.PopoverMenu",
	"ActionResult": {
		"_Name": "MenuTeam"
	},
	"PopoverItems": [
		{
			"Title": "Borrar equipo",
			"Icon": "sap-icon://delete",
			"Style": "",
			"OnPress": "/nba/Actions/CRUD/Delete/ConfirmDelete.action",
			"Visible": true,
			"Enabled": true
		},
		{
			"Title": "Editar",
			"Icon": "sap-icon://edit",
			"Style": "",
			"OnPress": "/nba/Actions/NavToEditTeam.action",
			"Visible": true,
			"Enabled": true
		}
	]
}