{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "AddMatchStatsResult"
	},
	"OnFailure": "/nba/Actions/FailAddMatchStats.action",
	"OnSuccess": "/nba/Actions/SuccessAddMatchStats.action",
	"Target": {
		"Service": "/nba/Services/NBA.service",
		"EntitySet": "JugadorSet",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"Puntos": "#Page:AddMatchStats/#Control:FCPuntos/#Value",
		"Asistencias": "#Page:AddMatchStats/#Control:FCAsistencias/#Value",
		"Rebotes": "#Page:AddMatchStats/#Control:FCRebotes/#Value",
		"Dobles": "#Page:AddMatchStats/#Control:FCDobles/#Value",
		"Triples": "#Page:AddMatchStats/#Control:FCTriples/#Value",
		"Minutos": "#Page:AddMatchStats/#Control:FCMinutos/#Value"
	}
}