{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "SuccessEditTeam"
	},
	"Message": "Equipo {NombreEquipo} editado exitosamente",
	"OKCaption": "OK",
	"OnOK": "/nba/Actions/ClosePage.action"
}